---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

params:
  CF_MANIFEST_HOST:

inputs:
  - name: pcfdemo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-integration

run:
  path: pcfdemo/ci/tasks/prepare-integration.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-integration,
    --version-file, version/number,
    --input-manifest, pcfdemo/manifest.yml,
    --packaging, tgz
  ]
